<?php

return [
    'database' => [
        'engine' => 'pgsql',
        'canonical_project' => env('TSG_SHARED_DATABASE_PROJECT', 'mobile-api'),
        'canonical_database' => env('TSG_SHARED_DATABASE_NAME', 'neondb'),
        'canonical_host_hint' => env('TSG_SHARED_DATABASE_HOST_HINT', 'neon.tech'),
    ],

    'required_tables' => [
        'users',
        'residents',
        'businesses',
        'services',
        'bookings',
        'business_approval_queue',
        'service_requests',
        'support_orders',
        'health_daily_metrics',
        'health_vitals',
        'guru_risk_scores',
        'wearable_devices',
        'audit_logs',
        'senior_living_communities',
        'senior_living_care_levels',
        'senior_living_resident_assignments',
        'senior_living_resident_import_batches',
        'tenants',
        'tenant_locations',
        'roles',
        'permissions',
        'model_has_roles',
        'tenant_user_memberships',
        'tenant_location_resident_assignments',
        'staff_profiles',
        'staff_assignments',
        'staff_tasks',
        'alert_triage_events',
        'incidents',
        'incident_events',
        'resident_events',
        'medication_schedules',
        'medication_events',
        'service_matches',
        'booking_events',
        'conversations',
        'messages',
        'notification_rules',
        'notification_logs',
        'broadcasts',
        'analytics_snapshots',
        'report_definitions',
        'generated_reports',
        'exports',
        'providers',
        'provider_services',
        'provider_service_areas',
    ],

    'node_owned_tables' => [
        'guru_risk_scores',
        'guru_health_insights',
        'guru_recommendations',
        'health_daily_metrics',
        'health_realtime_events',
        'wearable_telemetry',
        'safety_events',
        'transportation_context_decisions',
    ],

    'laravel_operations_tables' => [
        'businesses',
        'services',
        'bookings',
        'business_approval_queue',
        'business_leads',
        'business_photos',
        'business_documents',
        'tenants',
        'tenant_locations',
        'tenant_user_memberships',
        'tenant_location_resident_assignments',
        'staff_profiles',
        'staff_assignments',
        'staff_tasks',
        'alert_triage_events',
        'incidents',
        'incident_events',
        'resident_events',
        'medication_schedules',
        'medication_events',
        'service_matches',
        'booking_events',
        'conversations',
        'messages',
        'notification_rules',
        'notification_logs',
        'broadcasts',
        'analytics_snapshots',
        'report_definitions',
        'generated_reports',
        'exports',
        'providers',
        'provider_services',
        'provider_service_areas',
        'service_requests',
        'support_orders',
        'audit_logs',
        'senior_living_communities',
        'senior_living_care_levels',
        'senior_living_resident_assignments',
        'senior_living_resident_import_batches',
    ],

    'temporary_portal_only_tables' => [
        'communities',
        'community_services',
        'family_contacts',
        'resident_alerts',
        'vital_readings',
        'devices',
        'staff_shifts',
    ],
];
